env:
  matrix:
    secure: "FLBGA7zDxOO9p0zyxI5kcHxtCFX0hxwNq1kO0GLSQLuovj9b007aguaI2UhBkCBPlwJ9m8/yhr2Vf+dpCUn7ka7ro5A0qRhhPfs3eTb+qITINMlKOkZNsMI5fuYvwemhPXPDgDjumUsYWuCgj9IiJ9L9DS6Q9WmmyM5qpFTFNSfLmRHwJ9R4einF8Y0V+u2+QgqGSybuSAaokfXz4BUsRTuHpPD50s/0BFORG3+BxQqUcI1JymmygZG9T+3a8087DcVRJw2+536oVa/vRKsKRVQkayI8/Jgy/Qo70vRLB8zACruIg/PNFwtA0hbqB3KfS2FX+s9xah7a/BqTpSYRCbvmGGJFE6u2KpLRmM+Tuderu0h61wjOFZzGJiiFsN6U2SDV3UtDh382K8MLQMyQB9leKBNv3wUFH9x+jsaN5GshEZR1jp6jZgjCp4tR7COMjzXN+8qzMOvb/urqnNr23Ld+M+17YhefKZ9UH1nkgSXheeOjVLp580Yi/hFpuKdCI4KEy5ClWG/4wDoJxwli177JnQ3P9JzAUcjwLvBNSLmmB+FU3q0qCIUnAQUOzC8+752R5wTgmAZngYI89nf2+yOpV8gX9RvolgmvfJbFTBIYorbLhpI8wGeRqk8HgNi4yf/8GwsrjFIOAAaJKjxBGRSxfbDzPBbUBWhg0G5QPlM="
language: java

sudo: false

before_install:
  # - chmod a+x ./gradlew

script:
  - ./gradlew check
