= ```findanumber``` Documentation
Pascal Poizat @pascalpoizat
2020-10-25
:revnumber: {project-version}
:example-caption!:
ifndef::imagesdir[:imagesdir: images]
ifndef::sourcedir[:sourcedir: ../../main/java]
ifndef::modelsdir[:modelsdir: models]

// :reproducible:
// :numbered:
// :xrefstyle: short
// :figure-caption: Figure
// :listing-caption: Listing

== How to install?

=== If you have ```git``` on your computer

Simply run:
[source,shell]
----
git clone https://github.com/pascalpoizat/findanumber
----

=== If you do not have ```git``` on your computer

Go to https://github.com/pascalpoizat/findanumber, get the zipfile and uncompress it.

== How to run?

Simply run:
[source, shell]
----
./gradlew run
----

Does not work with Java 14. Use Java 11 or 12.

== What does ```findanumber``` do?

Well, not much (see below).

Here is the class diagram:

[plantuml, "class-diagram", svg, config="commons.style"]
.App class diagram
----
class App {
    - {static} GAME_HEADER: string = "Find a Number!" <<final>>
    + {static} game(nombreATrouver: int): void
    + {static} genererNombre(borneInf: int, borneSup: int): void
    + {static} main(args: string[*]): void
}
----

Here is the source code (using ```include``` but you can also put it directly):

[source,java]
.App source code
----
include::{sourcedir}/findanumber/App.java[indent=0]
----

Here is some code selection (using ```tag```):

[source,java]
----
include::{sourcedir}/findanumber/App.java[tag=contains,indent=0]
----

Still, it is quite fun to spend time playing with ```findanumber``` if you like number ```42```. Maybe soon available as an icon:android[] application.

== Last comments

Some books recommended with the course.

To learn all about design patterns, refer to the book by the "`Gang of Four`" <<gof>>.
Good practices are important. See <<ej3>> for example.
Some people refer to _The Pragmatic Programmer_ <<pp>>, that should be required reading for all developers. I still have to check this one.

[bibliography]
== References

- [[[ej3,1]]] Joshua Bloch. Effective Java, Third Edition. Pearson Education. 2018.
- [[[gof,2]]] Erich Gamma, Richard Helm, Ralph Johnson & John Vlissides. Design Patterns:
  Elements of Reusable Object-Oriented Software. Addison-Wesley. 1994.
- [[[pp,3]]] Andy Hunt & Dave Thomas. The Pragmatic Programmer:
  From Journeyman to Master. Addison-Wesley. 1999.
